### Specifications of EcoTaxa login information (required to export datasets hosted on EcoTaxa/EcoPart) ###
# Cut-paste lines 1:4, replace with appropriate credentials, and save as configuration_masterfile_pw.yalm (file on .gitignore)
ecotaxa_user : 'your Ecotaxa email login'
ecotaxa_pass : 'your Ecotaxa password'

### Specifications of PSSdb data, plots, and custom files sub-directories ###
# GIT repository
git_dir : '~/GIT/PSSdb/'

# General data storage sub-directory
dataset_subdir : 'raw'

# General figures storage sub-directory
figures_subdir : 'figures'
figures_standardizer : 'standardizer'

# Reports storage sub-directory
report_subdir : 'reports'

# Ancillary storage sub-directory
ancillary_subdir : 'reports'

#raw subdirectory: contains all data required for PSSdb including the list of imaging datasets, standardizers spreadsheets, raw data from imaging data streams, gridded and final NBSS products
raw_dir : '~/GIT/PSSdb/raw/'

#standardized raw subdirectory: contains all standardized datasets with harmonized variable headers and units
standardized_raw_subdir : 'raw_standardized'

# Ecotaxa exported files storage sub-directory : contains all raw datafiles exported from EcoTaxa
Ecotaxa_subdir : 'ecotaxa'

# Ecopart exported files storage sub-directory: contains all raw/detailed summaries exported from EcoPart
Ecopart_subdir : 'ecopart'

# Ecotaxa/Ecopart consolidated UVP exported files storage sub-direcotry: contains all UVP consolidated files with size estimates for small (EcoPart) and large (EcoTaxa) particles
UVP_consolidation_subdir: 'ecotaxa_ecopart_consolidation'
UVP_consolidation_metadata_subdir: 'ecotaxa_metadata'

#IFCB dashboard directory: contains the raw datafiles exported from IFCb dashboards
IFCB_dir : 'IFCB_dashboard_downloads'


#standadrized datasets storage sub-subdirectory
standardized_subdir : 'raw/raw_standardized'

#binned datasets storage sub-subdirectory: contains gridded standardized datafiles
gridded_subdir : 'gridded_data'

#Summary datasets storage subdirectory: contains a summary of datasets samples location, timestamp, study area, and flag
summary_subdir : 'summary'

#Flag datasets storage subdirectory: contains project-specific datatables including the flag returned after control quality check
flag_subdir : 'flags'

# Path to project_list_all.xlsx: The list of imaging datasets generated automatically using API
proj_list : 'raw/project_list_all.xlsx'

# Path to custom units definition: The list of custom units definition needed for datasets standardization
units_file : 'scripts/units_def.txt'

# Path to taxonomic lookup table: The list of taxonomic annotations matched to the World Ocean Marine Species database automatically using API
annotations_lookup : 'ancillary/plankton_annotated_taxonomy.xlsx'

# Path to allometric lookup table: The list of taxonomic or functional groups with published allometric relationships linking size to biomass
allometry_lookup : 'ancillary/plankton_elemental_quotas.xlsx'

### Specifications for instrument, gridding, binning and averaging NBSS products ###

day_night: 'N' # or 'Y'
depth_binning: 'N' # or 'Y'
depth_bins: [0, 25, 50, 100, 200, 500, 1000, 3000, 8000] # Customize with desired depth bins

st_increment: 0.5 # size of the grid used in step3_gridding_func
date_group: 'week' # time interval to bin data in step3_gridding_func. Other options:  'mm' (month), 'yyyymm' (year-month), 'yyyy' (year)
keep_cats: 'N' # or 'Y'
cats_to_keep: [] # fill if you want to keep any of the categories such as ['beads','detritus', 'artefact', 'bubble', 'plastic']

N_test: 0 # number of files to be gridded, 0 means all. This is useful for debugging the pipeline

st_increment_avg: 1 #size of the grid used for averaging in step4_compute_NBSS
date_group_avg: 'yyyymm' #time interval for averaging in step4_compute_NBSS. Other options:  'mm' (month), 'yyyy' (year)
big_grid: 'N' #  'Y' or 'N'
size_bins_path: '~/GIT/PSSdb/raw/ecopart_size_bins.tsv'
