# Ecotaxa login
# Cut-paste lines 1:4, replace with appropriate credentials, and save as Ecotaxa_API_pw.yalm (file on .gitignore)
ecotaxa_user : 'your Ecotaxa email login'
ecotaxa_pass : 'your Ecotaxa password'


# GIT repository for storage
git_dir : '~/GIT/PSSdb/'

#raw subdirectory
raw_dir : '~/GIT/PSSdb/raw/'

#standardized raw subdirectory
standardized_raw_subdir : 'raw_standardized'

# Ecotaxa exported files storage sub-directory :
Ecotaxa_subdir : 'ecotaxa'

# Ecopart exported files storage sub-directory:
Ecopart_subdir : 'ecopart'

# Ecotaxa/Ecopart consolidated UVP exported files storage sub-direcotry (git_dir/Data)
UVP_consolidation_subdir: 'ecotaxa_ecopart_consolidation'
UVP_consolidation_metadata_subdir: 'ecotaxa_metadata'

#IFCB dashboard directory:
IFCB_dir : 'IFCB_dashboard_downloads'

# General data storage sub-directory
dataset_subdir : 'raw'

#standadrized datasets storage sub-subdirectory
standardized_subdir : 'raw/raw_standardized'

#binned datasets storage sub-subdirectory
gridded_subdir : 'gridded_data'

#Summary datasets storage subdirectory
summary_subdir : 'summary'

#Flag datasets storage subdirectory
flag_subdir : 'flags'

# Path to project_list_all.xlsx
proj_list : 'raw/project_list_all.xlsx'

# Numeric id of project to download
# you should have appropriate access rights to it:
# - either the project should be visible to all
# - or you should be explicitly registered to it, as viewer at least
proj_id : 3302


### Specifications for instrument, gridding, binning and averaging NBSS products
instrument_data_source: 'Zooscan' # other choices: 'Zooscan', 'UVP'
day_night: 'N' # or 'Y'
depth_binning: 'N' # or 'Y'

st_increment: 0.5 # size of the grid used in step3_gridding_func
date_group: 'week' # time interval to bin data in step3_gridding_func. Other options:  'mm' (month), 'yyyymm' (year-month), 'yyyy' (year)
keep_cats: 'N' # or 'Y'
cats_to_keep: [] # fill if you want to keep any of the categories such as ['beads','detritus', 'artefact', 'bubble', 'plastic']

depth_bins: [0, 25, 50, 100, 200, 500, 1000, 3000, 8000] # Customize with desired depth bins
N_test: 0 # number of files to be gridded, 0 means all. This is useful for debugging the pipeline


st_increment_avg: 1 #size of the grid used for averaging in step4_compute_NBSS
date_group_avg: 'yyyymm' #time interval for averaging in step4_compute_NBSS. Other options:  'mm' (month), 'yyyy' (year)
big_grid: 'N' #  'Y' or 'N'
size_bins_path: '~/GIT/PSSdb/raw/ecopart_size_bins.tsv'